name: Nightly Update

on:
  schedule:
    - cron: '0 0 * * *' # Runs every night at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use the desired Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Run Data Script
      run: node fetchAndProcessData.js

    - name: Commit Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add output/
        git diff --quiet || git commit -m "Update data files"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Update data files
        branch: update-data-files
        title: Update Data Files
        body: | 
          This automated pull request updates the data files.
